---
- name: Install test
  hosts: GK
  become: True

  tasks:
  - name: Install programm
    dnf: name=cifs-utils
  - name: Install pam_mount
    dnf: name=pam_mount
  - name: Copy file config
    copy: src=/etc/ansible/pam_mount.conf.xml dest=/etc/security/
  - name: create Directory
    file:
      path=/mnt/GK
      mode=0664
      state=directory
  - name: LinkHOME
    file:
      src="/mnt/GK"
      dest="/home/%USER/Рабочий стол/Женская консультация2"
      state=link

- name: KRB5
  hosts: GK
  become: True

  tasks:
  - name: Add a line
    lineinfile:
      path: /etc/pam.d/postlogin
      line: session optional pam_mount.so disable_interactive
      state: present
      create: yes
