---
- name: JAVA and nginx
  hosts: My
  become: True

  tasks:
    - name: Remove JDK
      dnf:
        name: java-1.8.0-openjdk
        state: absent
        update_cache: true
    - name: nginx
      dnf:
        name: nginx
        state: latest
        update_cache: true
    - name: copy nginx conf file
      copy: src=files/nginx.conf dest=/etc/nginx/
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
    - name: Service nginx enabled
      service:
        name: nginx
        state: started
        enabled: yes
- name: Install JAVA 17
  hosts: My
  become: True
  roles:
    - role: java_install
      java_packages:
        - java-17-openjdk