
---
# tasks file for java_install
- name: Remove JDK
  dnf:
    name: java-1.8.0-openjdk
    state: absent
    update_cache: true

- name: Download the JDK binaries
  get_url:
    url: "{{ jdk_download_url }}"
    dest: "{{ jdk_download_location }}"

- name: Unzip the downloaded file
  unarchive:
    src: "{{ jdk_download_location }}"
    dest: /opt
    remote_src: yes

- name: Java alternatives
  alternatives:
    name: java
    path: /opt/jdk-17.0.2/bin/java
    link: /usr/bin/java

- name: Delete download file
  file:
    dest: "{{ jdk_download_location }}"
    state: absent